// swift-tools-version:5.1
import PackageDescription

let package = Package(name: "AdventOfCode2019",
                      platforms: [
                        .macOS(.v10_14)
                      ],
                      products: [
                        .library(name: "AdventOfCode", targets: [ "AdventOfCode" ]),
                        .executable(name: "Day01", targets: [ "Day01" ]),
                        .executable(name: "Day02", targets: [ "Day02" ]),
                        .executable(name: "Day03", targets: [ "Day03" ]),
                        .executable(name: "Day04", targets: [ "Day04" ]),
                        .executable(name: "Day05", targets: [ "Day05" ]),
                        .executable(name: "Day06", targets: [ "Day06" ]),
                        .executable(name: "Day07", targets: [ "Day07" ]),
                        .executable(name: "Day08", targets: [ "Day08" ]),
                        .executable(name: "Day09", targets: [ "Day09" ]),
                        .executable(name: "Day10", targets: [ "Day10" ]),
                        .executable(name: "Day11", targets: [ "Day11" ]),
                        .executable(name: "Day12", targets: [ "Day12" ]),
                        .executable(name: "Day13", targets: [ "Day13" ]),
                        .executable(name: "Day14", targets: [ "Day14" ]),
                        .executable(name: "Day15", targets: [ "Day15" ]),
                        .executable(name: "Day16", targets: [ "Day16" ]),
                        .executable(name: "Day17", targets: [ "Day17" ]),
                        .executable(name: "Day18", targets: [ "Day18" ]),
                        .executable(name: "Day19", targets: [ "Day19" ]),
                        .executable(name: "Day20", targets: [ "Day20" ]),
                        .executable(name: "Day21", targets: [ "Day21" ]),
                        .executable(name: "Day22", targets: [ "Day22" ]),
                        .executable(name: "Day23", targets: [ "Day23" ]),
                        .executable(name: "Day24", targets: [ "Day24" ]),
                        .executable(name: "Day25", targets: [ "Day25" ]),
                      ],
                      dependencies: [
                        .package(url: "https://github.com/peterkovacs/FootlessParser.git", .branch( "inout-remainder" )),
                      ],
                      targets: [
                        .target(name: "AdventOfCode", dependencies: [ "FootlessParser" ]),
                        .target(name: "Day01", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day02", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day03", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day04", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day05", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day06", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day07", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day08", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day09", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day10", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day11", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day12", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day13", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day14", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day15", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day16", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day17", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day18", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day19", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day20", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day21", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day22", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day23", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day24", dependencies: [ "AdventOfCode" ]),
                        .target(name: "Day25", dependencies: [ "AdventOfCode" ]),
                       ]
 )
